//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyHandler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoneyHandler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;currencies&gt;
        ///	&lt;currency code=&quot;AED&quot;&gt;
        ///		&lt;englishName&gt;UAE Dirham&lt;/englishName&gt;
        ///		&lt;nativeName&gt;درهم اماراتي&lt;/nativeName&gt;
        ///		&lt;symbol&gt;1583 46 1573 46 8207&lt;/symbol&gt;
        ///		&lt;significantDecimalDigits&gt;2&lt;/significantDecimalDigits&gt;
        ///		&lt;decimalSeparator&gt;.&lt;/decimalSeparator&gt;
        ///		&lt;groupSeparator&gt;,&lt;/groupSeparator&gt;
        ///		&lt;groupSizes&gt;3&lt;/groupSizes&gt;
        ///		&lt;positivePattern&gt;2&lt;/positivePattern&gt;
        ///		&lt;negativePattern&gt;3&lt;/negativePattern&gt;
        ///	&lt;/currency&gt;
        ///	&lt;currency code=&quot;AFN&quot;&gt;
        ///		&lt;engli [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Currencies {
            get {
                return ResourceManager.GetString("Currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be of type &apos;MoneyHandler.Money&apos;.
        /// </summary>
        internal static string Str_Money_ThrowInvalidArgumentTypeException {
            get {
                return ResourceManager.GetString("Str_Money_ThrowInvalidArgumentTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown parse error.
        /// </summary>
        internal static string Str_Money_UnknownParseError {
            get {
                return ResourceManager.GetString("Str_Money_UnknownParseError", resourceCulture);
            }
        }
    }
}
